### ISSUE TITLE
No results

### ISSUE THREAD

**Issue by ArtsieFy** [Duelsik/beatsaber-request-ui#9]
No song are found no matter what even uninstalling the extension and reinstalling it see images attached songs are on beat saver but the extension does NOT work
![Extention](https://user-images.githubusercontent.com/98577285/151499893-fcd50c57-cb32-46b6-bf79-3f480760cf6b.png)
![BeatSaver](https://user-images.githubusercontent.com/98577285/151499902-ec1cf0a6-8fac-487b-8f3a-5c6d12764b97.png)
!

**Comment by Duelsik** [comment]
Hello and thank you for posting the issue,
I've checked the extension on your channel and configuration looks fine. Search query works for me.
Could you reverify if the problem still happems? (it could be a brief outage on beatsaver api part, while it was serving homepage from cache)

**Comment by Duelsik** [comment]
(forgotten to use mention - @ArtsieFy ^)

**Comment by ArtsieFy** [comment]
It still does not work for me should I perhaps clear my cache?

**Comment by Duelsik** [comment]
@ArtsieFy I think it might help, but - if you don't need use this extension right now... I would like to doublecheck if there are no errors on my end (your case might go into very rare scenario)
Could you say what browser and at which version do you use? It usually is in this dropdown menu (3 vertical dots) on the top right and then it will show you "about" menu option.

**Comment by ArtsieFy** [comment]
HI no I dont need it right now as I am only streaming Beat saber again on Monday :) current version Version 97.0.4692.99 (Official Build) (64-bit) of Chrome and thank you for the support!!!

**Comment by Duelsik** [comment]
@ArtsieFy found issue, it happens only on desktop browsers tho. Thanks for the report, will try to roll out an update during this weekend (plus most likely a week due to twitch verificators :P)

**Comment by ArtsieFy** [comment]
Thank you SO MUCH ! I appreciate it

**Comment by ArtsieFy** [comment]
Hi just dropping by to see if you have any update yet :) hope you are doing well

**Comment by F1ltr** [comment]
Hello, I got the same problem today.  Mobile and desktop versions

**Comment by Duelsik** [comment]
Sorry for the delay, but I got no response from beatsaver devs about something crucial. I will make a deploy and we will see if there will be problems :/
Thank you for waiting.

**Comment by Duelsik** [comment]
Sent for verification :champagne:

**Comment by Duelsik** [comment]
Twitch responded that they have some problems with my extension, will check if I did a mistake.
Generally they can't run non-panel version of the extension - this one that renders on top of stream video.

Will recheck and repush it :eyes:

**Comment by Duelsik** [comment]
Rechecked on my side, run empty stream to see the overlay extension working. It works flawlessly.

Resending the verification ticket.
// Love the Twitch Developer Experience team.

**Comment by Duelsik** [comment]
... So to not randomly fail verification... I play only BeatSaber xD

**Comment by Duelsik** [comment]
The extension got approved :champagne: 
Since there is no configuration change... your panels should be automatically updated.
If there will be any problems - feel free to open new issue.
Thanks for patience <3

cc @ArtsieFy @F1ltr
